### ISSUE TITLE
Improved deployment

### ISSUE THREAD

**Issue by clkao** [datproject/docs#10]
1. Improve gh-pages so we know built tree vs source tree: https://github.com/tschaub/gh-pages/issues/91
2. post-commit deployment via travis

**Comment by joehand** [comment]
Added deployment via travis!

I made it so it'll auto deploy anything pushed to the deploy branch.

> Improve gh-pages so we know built tree vs source tree: tschaub/gh-pages#91

Not sure what this means...

**Comment by joehand** [comment]
But we still need to auto deploy when a readme for one of the modules used in docs updates (e.g. dat cli, hyperdrive, etc.). 

I thought maybe we could use greenkeeper to do this if we just add those modules as dependencies?

**Comment by joehand** [comment]
Hmm. Maybe this won't work on the [deploy branch](https://travis-ci.org/datproject/docs/builds/184838993#L1150).

> Skipping a deployment with the script provider because this branch is not permitted

**Comment by joehand** [comment]
> Still need to auto deploy when a readme for one of the modules used in docs updates (e.g. dat cli, hyperdrive, etc.).

**Comment by joehand** [comment]
Close enough =). We are using netlify now.

It does not auto deploy with when sub modules are updated but we can do that with single click if its important enough update.
