### ISSUE TITLE
use readme.md for instructions on editing/deploying docs

### ISSUE THREAD

**Issue by karissa** [datproject/docs#11]
and then use index.md or maxogden/dat/readme.md for the rendered docs

**Comment by joehand** [comment]
@clkao I tried changing the [index page](https://github.com/datproject/docs/tree/index-page) but the deploy didn't work. The CNAME file went missing and no index.html page was generated. Am I missing a step in the deploy?

**Comment by clkao** [comment]
apparently index.md will cause minidocs to have collision and fail.  I moved the current content to welcome.md and got us a fresh readme now.

**Comment by karissa** [comment]
nice!
