### ISSUE TITLE
datproject.org download demo deletes current working directory.

### ISSUE THREAD

**Issue by TimothyStiles** [datproject/docs#113]
Hey folks,

Just ran the code below from [dat's documentation](https://docs.datproject.org/diy-dat#download-a-file) and when I ran it it deleted my working directory and the code I was working on. Not sure why yet but I thought I'd share it here before I forget. Any ideas on what happened? I hope it's just my own error and new users aren't accidentally deleting their work!
![screen shot 2018-03-29 at 3 33 01 pm](https://user-images.githubusercontent.com/7042260/38109564-8bebd9a8-3366-11e8-8f9d-c6a8790188c8.png)

```node
var ram = require('random-access-memory')
var hyperdrive = require('hyperdrive')
var discovery = require('hyperdiscovery')
var mirror = require('mirror-folder')

var link = process.argv[2] // user inputs the dat link
var key = link.replace('dat://', '') // extract the key
var dir = process.cwd() // download to cwd

var archive = hyperdrive(ram, key)
archive.ready(function () {
  discovery(archive)

  var progress = mirror({name: '/', fs: archive}, dir, function (err) {
    console.log('done downloading!')
  })
  progress.on('put', function (src) {
    console.log(src.name, 'downloaded')
  })
})
```

**Comment by joehand** [comment]
Oh no! Darn, sorry about that!

Mirror-folder makes the two directories look the same, which means deleting local stuff if it doesn't exist on the archive. No good for this example!

```js
var mkdirp = require('mkdirp')
...
var dir = path.join(process.cwd(), 'download') // CHANGE DOWNLOAD DIR
mkdirp.sync(dir) // make dir

...
```

**Comment by joehand** [comment]
Updated https://github.com/datproject/docs/blob/master/docs/cookbook/diy-dat.md#download-all-files-to-computer

Thanks for opening this!
