### ISSUE TITLE
Hypercore specification missing "Basic Privacy" information

### ISSUE THREAD

**Issue by tswast** [datproject/docs#120]
I was looking for docs on how the discovery key and public key are used, but found only a placeholder for the "Basic Privacy" section at https://github.com/datproject/docs/blob/master/docs/hyperdrive_spec.md#basic-privacy

**Comment by joehand** [comment]
Thanks, you can find the latest specification information in the DEPs: https://github.com/datprotocol/DEPs. You can find more about the keys in this WIP DEP on peer discovery https://github.com/pfrazee/DEPs/blob/653e0cf40233b5d474cddc04235577d9d55b2934/proposals/0000-peer-discovery.md
