### ISSUE TITLE
Typo on dat/concepts webpage

### ISSUE THREAD

**Issue by DougAnderson444** [datproject/docs#138]
On [Dat Website](https://docs.datproject.org/concepts) under section "**dat:// links**" it says: 

> "With the hex string as a link we can a few things:"

I think it means to say something like "we can do a few things". Cheers

**Comment by DougAnderson444** [comment]
I'm new to GitHub, not sure if I've done the PR correctly it's status is "Closed"

**Comment by bnewbold** [comment]
Thanks!
