### ISSUE TITLE
Missing image asset on CLI docs

### ISSUE THREAD

**Issue by todrobbins** [datproject/docs#151]
[This section](https://docs.datproject.org/docs/cli-intro#sharing-data) links to an old image asset (GIF) that is missing:

<img width="843" alt="Screen Shot 2019-04-12 at 9 48 58 PM" src="https://user-images.githubusercontent.com/158590/56074289-cc7b6200-5d6c-11e9-9aaa-5d4447053253.png">

The link is to `https://raw.githubusercontent.com/datproject/docs/master/assets/cli-share.gif`, but it no longer exists as far as I can tell. Is there a replacement that could fit here instead?

**Comment by whoisgina** [comment]
Here are those gifs:
Share: 
https://github.com/datproject/docs/blob/079395f55df778af0fc87bad8730ca62462201c8/assets/cli-share.gif

Clone:
https://github.com/datproject/docs/blob/079395f55df778af0fc87bad8730ca62462201c8/assets/cli-clone.gif

They're 3 years old though! If they're not out of date (please advise when you're back @joehand!) we could put them back in there.

**Comment by karissa** [comment]
These are up to date but by the end of the year we are aiming to release a new version of the cli which will likely change this,

**Comment by todrobbins** [comment]
I think we should put them back for now 🤷🏻‍♂️
