### ISSUE TITLE
Build error with `npm install` - Cookbook Simple chat

### ISSUE THREAD

**Issue by Saul-BT** [datproject/docs#173]
When I try to supply all dependencies from [kappa-workout package.json](https://gist.github.com/mafintosh/a642bf514cb6aa583fa8b1a6b1782f19) it throws some errors:

<pre>
make: *** [utp.target.mk:117: Release/obj.target/utp/src/socket_wrap.o] Error 1
make: se sale del directorio '/home/tarod/Documentos/prueba-dat/kappa-workshop/node_modules/utp-native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.5.13-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tarod/Documentos/prueba-dat/kappa-workshop/node_modules/utp-native
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
</pre>

Node version: v13.12.0
NPM version: 6.14.4

**Comment by okdistribute** [comment]
Ah @Saul-BT, instead of discovery-swarm, try using hyperswarm -- the docs might need updating.. Or otherwise, try downgrading to node 8.

**Comment by okdistribute** [comment]
cc @noffle this gist could be updated to be more accurate, it is old https://github.com/kappa-db/workshop/blob/master/problems/02.md

**Comment by Saul-BT** [comment]
Yep, I noticed 😊

**Comment by okdistribute** [comment]
OK Should be fixed now https://github.com/kappa-db/workshop/commit/dae4c8e1ec15d93b78bac26744fb06054dfa7ff8

**Comment by Saul-BT** [comment]
> OK Should be fixed now [kappa-db/workshop@dae4c8e](https://github.com/kappa-db/workshop/commit/dae4c8e1ec15d93b78bac26744fb06054dfa7ff8), please let us know if that isn't correct.

It's correct, but I have found several problems following the workshop.
When I finish the workshop, I will send a PR with the fixes :).

Thanks @okdistribute

**Comment by okdistribute** [comment]
thanks @Saul-BT ! that's helpful, we wrote it over a year ago and the ecosystem has been moving!

**Comment by Saul-BT** [comment]
> > OK Should be fixed now [kappa-db/workshop@dae4c8e](https://github.com/kappa-db/workshop/commit/dae4c8e1ec15d93b78bac26744fb06054dfa7ff8), please let us know if that isn't correct.
> 
> It's correct, but I have found several problems following the workshop.
> When I finish the workshop, I will send a PR with the fixes :).
> 
> Thanks @okdistribute

Here it is: kappa-db/workshop#22
