### ISSUE TITLE
dat logo not available from dat-design

### ISSUE THREAD

**Issue by sethvincent** [datproject/docs#20]
Since the downloads folder of dat-design is [listed in .npmignore](https://github.com/datproject/design/blob/master/.npmignore) the build scripts in this repo are failing to copy the dat-data-logo.png file.

I tried using the svg logo in the public dir of dat-design instead and that works fine. I could send a PR for that.

(Testing minidocs changes and happened across this.)

**Comment by karissa** [comment]
yes!
