### ISSUE TITLE
Terms

### ISSUE THREAD

**Issue by joehand** [datproject/docs#26]
> 2:46 PM <notwes> is there a term reference around?  something like this: https://camlistore.org/doc/terms
> 2:46 PM <notwes> it would be nice to know specifically what an "archive" means, or what a "dat-key" is vs a "discovery key".

Random brain dump to start below.

Terminology we use across the Dat Project.

### Dat Key

`dat://<hash>`

### Discovery Key

Hashed key for connected to peers over the newtwork.

### Hyper- (modules)

e.g. hyperdiscovery, hyperhealth. 

A module that works with hyperdrive archive and hypercore feeds.

**Comment by zeke** [comment]
Sweet! I would love to know more about what all these terms mean and how they fit together.

Relatedly, we just started an Electron glossary: https://github.com/electron/electron/blob/master/docs/glossary.md

**Comment by karissa** [comment]
Started it here:

https://github.com/datproject/docs/pull/28/files

let's flesh it out and push soon!
