### ISSUE TITLE
FAQ: Link to a specific question

### ISSUE THREAD

**Issue by joehand** [datproject/docs#37]
It'd be nice to have a link icon thing so we can get permalinks to specific questions. Minidocs gives IDs but still probably some PR there for the link icon.

**Comment by millette** [comment]
Yes, like these: https://docs.datproject.org/faq#how-do-dat-peers-discover-one-another-on-the-internet

It's a valid point for all docs pages, not only the FAQ.

I tiny bit of client-side JS could show a # on hover, as in GitHub Readme pages.
