### ISSUE TITLE
datfolder.org link is relative

### ISSUE THREAD

**Issue by srenatus** [datproject/docs#43]
In `[terms.md](https://github.com/datproject/docs/blob/6abe36a66a77f33142c625a03a4b5af525aa515d/docs/terms.md#L41)` line 41 (github doesn't give you links to lines in markdown files, it seems), the reference is relative,

```
We maintain an open register called [Dat Folder](datfolder.org) which contains public data, and is open to everyone.
```

and thus doesn't work. I'd fix it, but I'm not sure _where it should link to_:http://datfolder.org gives me a 503; https://datfolder.org forwards to some other page so its certificate's name mismatches (cert says `beta.datproject.org`).

Thanks!

**Comment by karissa** [comment]
Nice catch, it should be `datproject.org`
