### ISSUE TITLE
Scrolling down and clicking a new page

### ISSUE THREAD

**Issue by karissa** [datproject/docs#62]
if i scroll down on one page and click a new page it doesn't go to the top. that's new with the minidocs fork, i don't see the same behavior on example minidocs pages

**Comment by karissa** [comment]
@joehand do you know why this might be happening? i wonder if it's an easy fix

**Comment by joehand** [comment]
Seems like this isn't getting called for some reason: https://github.com/datproject/minidocs/blob/dat-tachyons/app.js#L35-L42

I can take look tomorrow.

**Comment by joehand** [comment]
fixed https://github.com/datproject/minidocs/commit/7447df6800ba6dfea63ea77705cc39125600b455
