### ISSUE TITLE
Dat Network Protocol specification needs to be updated

### ISSUE THREAD

**Issue by aschrijver** [datproject/docs#70]
For my [message layer](https://github.com/datproject/discussions/issues/64) research wrt `hypercore-protocol` I was referred to the [dat network protocol](https://github.com/datproject/docs/blob/master/papers/dat-paper.md#4-dat-network-protocol) specification, but found it outdated in places.

For instance message no. 0 is called `Register` but in `schema.proto` it has become `Feed`.

I have made a proposal in Discussions project to auto-generate docs from `schema.proto`:
- [Auto-generate protocol documentation from inline comments in schema.proto](https://github.com/datproject/discussions/issues/66)

**Comment by aschrijver** [comment]
Demonstration + documentation of auto-generation options using TravisCI

- https://github.com/aschrijver/hypercore-protocol/tree/feature/document-generator

**Comment by joehand** [comment]
Nice! We use [ecosystem-docs](https://github.com/hughsk/ecosystem-docs) to pull in data from other repositories and display on the docs page, e.g. [hypercore readme](https://docs.datproject.org/hypercore). I wonder if we can hack that to pull in the auto doc page?

Feel free to PR any error in the paper . We should definitely have that be correct as well!

**Comment by aschrijver** [comment]
All the docs are now in the specs of my test document. Probably with some tweaking the doc can be added to the correct location of docs.datproject.org (either triggered from `docs` or from `hypercore-protocol` project travis-ci build.
