### ISSUE TITLE
Update outdated apidocs (options, methods, method sigs, events)

### ISSUE THREAD

**Issue by aschrijver** [datproject/docs#75]
The [hypercore API](https://docs.datproject.org/hypercore#api) documentation refers to the options that can be passed to various methods ('_options include: ..._`).

But the documentation only details a subset of supported options. For other options you have to dive into the code of the hypercore repo (which is not linked from the page).

Full set of options are

```javascript
{
  createIfMissing: true, // create a new hypercore key pair if none was present in storage
  overwrite: false, // overwrite any old hypercore that might already exist
  valueEncoding: 'json' | 'utf-8' | 'binary', // defaults to binary
  sparse: false, // do not mark the entire feed to be downloaded
  secretKey: buffer, // optionally pass the corresponding secret key yourself
  storeSecretKey: true, // if false, will not save the secret key

  // undocumented options
  id: null,
  live: null,
  maxRequests: null,
  writable: null,
  allowPush: null,
  indexing: null
}
```

PS: As I'm creating this issue I found more methods, such as `proof` which are completely undocumented and also have an `options` argument, and `clear` which has an added `opts` parameter that is undocumented. So I changed the title from 'Update options' to 'Update docs'.

**Comment by aschrijver** [comment]
Same findings on `hyperdrive` API docs (missing options, undocumented events, stat explanation or link to `fs.stat` docs missing) and - though more complete - in `dat-node` (undocumented `opts.latest`, `opts.temp`, missing `opts.errorIfExists`, `opts.indexing`, callback doesn't reflect code, inline jsdocs also not up-to-date)

So I will generalize the issue title a bit further.

**Comment by joehand** [comment]
Thanks, we definitely moved code faster than docs in the last few months. 

It'd be great if you could PR these directly to the relevant repos. Even just starting a PR with placeholders or (TODO) notes would be really helpful. Then we can work to fill in the missing parts.

**Comment by aschrijver** [comment]
Ya, but my todo's + follow-up updates will only be a temporary patch. Having the API docs separately in a README is asking for problems, imho. The next code update will make then out-of-sync again.

Dat Project and its (official) modules are a technology framework for 3rd party developers, where good, up-to-date API docs are vitally important. When out-of-date you oblige developers to carefully scan through the code to find out how to use it.

I would strongly advise to have inline JSDoc comments, like in `dat` (though only in `index.js`). Then you have code and apidocs in one place, making it easier to keep in sync. Then auto-generate + publish to docs.datproject.org

Besides that, a review of documentation (both user and API) besides regular code review should be part of the Definition of Done for a PR, so it is never forgotten.
