### ISSUE TITLE
Interesting documentation missing from ToC

### ISSUE THREAD

**Issue by aschrijver** [datproject/docs#77]
I found that 2 interesting pages with more in-depth design details are not linked in the docs, nor the toc.

- [How Dat works](https://github.com/datproject/docs/blob/master/docs/how-dat-works.md)
- [Hyperdrive + Hypercore Specification](https://github.com/datproject/docs/blob/master/docs/hyperdrive_spec.md) (referenced from the first page)

are not in [contents.json](https://github.com/datproject/docs/blob/master/docs/contents.json).

**Comment by ralphtheninja** [comment]
Is that spec in sync with current [schema.proto](https://github.com/mafintosh/hypercore-protocol/blob/master/schema.proto)? There's also https://www.datprotocol.com/spec.html , which seems to be the same document (not sure if it's identical)

**Comment by aschrijver** [comment]
I believe the datprotocol.com is old, needs to be updated. First glance: it is outdated in a number of places.

PS. I created a demo of having the specification docs autogenerated from the `.proto` (see [demo](https://github.com/aschrijver/hypercore-protocol/tree/feature/document-generator) + [issue](https://github.com/datproject/discussions/issues/66)

**Comment by karissa** [comment]
yes datprotocol.com is outdated

**Comment by karissa** [comment]
@mafintosh @maxogden is https://github.com/datproject/docs/blob/master/docs/how-dat-works.md still up to date? we could re-enable it on the sidebar if so. I forget why it was removed
