### ISSUE TITLE
use ecosystem-docs to include module api references

### ISSUE THREAD

**Issue by clkao** [datproject/docs#8]

**Comment by joehand** [comment]
@clkao how do you see this working? 

It'd be great to have all the dat ecosystem docs in one place, but I want to make the docs are self-contained with modules for two reasons:

1. We want to make sure they are easy to update for each module. It's a pain to have to update the docs site separately from the module.
2. Allows users to see docs for one module without clicking through others/main site.

**Comment by karissa** [comment]
Makes sense to me. I think minidocs has this build in, right?
