### ISSUE TITLE
publish.md describes functionality that does not seem to work or may not exist yet.

### ISSUE THREAD

**Issue by TimothyStiles** [datproject/docs#80]
[publish.md](https://github.com/datproject/docs/blob/master/docs/cookbook/publish.md) describes functionality that allows users to clone dats using dat.json as described in this [feature request](https://github.com/datproject/dat/issues/639). This feature does not seem to be implemented yet (see my comment on [feature request](https://github.com/datproject/dat/issues/639)). Should [publish.md](https://github.com/datproject/docs/blob/master/docs/cookbook/publish.md) be edited to reflect this?

**Comment by ralphtheninja** [comment]
@TimothyStiles Oh, we bumped into the same thing.

**Comment by TimothyStiles** [comment]
Fixed in #83 and Dat PR [847](https://github.com/datproject/dat/pull/847).
