### ISSUE TITLE
How can I change or recover my password?

### ISSUE THREAD

**Issue by zeke** [datproject/docs#85]
👋 

Trying to log in, but it seems I'm using the wrong password. Is there a way to change it?

```
$ dat login
Welcome to dat program!
Login to publish your dats.

Dat registry:  (datproject.org) 
Email:  zeke@sikelianos.com
Password:  ************

Password incorrect.

$ dat --version
13.8.1
```

**Comment by sethvincent** [comment]
I think you can do it here: https://datproject.org/reset-password

Seems like there's not a command for it currently.

**Comment by zeke** [comment]
🙏
