### ISSUE TITLE
JS bundle is semi-broken (links don't work thru js)

### ISSUE THREAD

**Issue by millette** [datproject/docs#99]
On firefox 57, with no content blocked (according to ublock extension) the left sidebar links don't work when clicked. Well, the URL changes in the location bar, but the content remains the same. Visiting a page directly properly shows it's content.

For instance,open <https://docs.datproject.org/> and click [Installation](https://docs.datproject.org/install) from the sidebar. On the other hand, if you click [Installation](https://docs.datproject.org/install) here, it works as expected.

I'm seeing these errors in the js console:
```
Blocage du chargement du contenu mixte actif (mixed active content) « http://fonts.gstatic.com/s/bitter/v12/zfs6I-5mjWQ3nxqccMoL2A.woff2 »
[En savoir plus]
docs.datproject.org
21:11:41,323
TypeError: node is null
[En savoir plus]
bundle.js:7921:1
21:18:11,831 uncaught exception: AssertionError: nanoraf: new frame was created before previous frame finished
```

**Comment by millette** [comment]
Seems like this was fixed, maybe 1h ago. Closing, yay!

**Comment by millette** [comment]
Ping! It's broken again.

**Comment by bnewbold** [comment]
This must be flapping... I checked just now with slightly older firefox and chrome and saw no problems.
Maybe reply here or ping on IRC when it's broken for you and we can try to reproduce?

**Comment by millette** [comment]
Just had another look and it's working alright. Nothing in the js console either. When it fails, the console gets pretty noisy (see OP).
